CREATE DATABASE IF NOT EXISTS user;
DROP SCHEMA if EXISTS user;

CREATE SCHEMA user;

USE user;



CREATE TABLE user(
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(255),

    PRIMARY KEY (id)
);
CREATE TABLE book_Id(
    id BIGINT NOT NULL AUTO_INCREMENT,
#     user_id BIGINT,

    PRIMARY KEY(id)

);