server:
  port: 8000

spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      enabled: true
      discovery:
        query-passing: true
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${random.value}
      config:
        data-key: application.yml
        format: yaml
        default-context: defaults
        prefixes:
    gateway:
      routes:
        - id: book
          uri: lb://book
          predicates:
            - Path=/book/**

        - id: manager
          uri: lb://manager
          predicates:
            - Path=/manager/**

        - id: comment
          uri: lb://comment
          predicates:
            - Path=/comment/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
    globalcors:
      cors-configurations:
        '[/**]':
          allowed-origins:
            - "http://localhost:3000"
          allowed-headers:
            - "*"
          allowed-methods:
            - "GET"
            - "POST"
            - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET, POST

logging:
  level:
    org.springframework.cloud.gateway: INFO