volumes:
  book_db:
    driver: local
  comment_db:
    driver: local
services:
  book_db:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=Kakemann'
      - 'MYSQL_ROOT_USER=root'
    volumes:
      - ./mysql/book/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    networks:
      - services
  comment_db:
    image: 'mysql:latest'
    healthcheck:
      test: ls
      interval: 30s
      start_period: 30s
    environment:
      - 'MYSQL_ROOT_PASSWORD=Kakemann'
      - 'MYSQL_ROOT_USER=root'
    volumes:
      - ./mysql/comment/init:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    networks:
      - services
  consul:
    image: 'hashicorp/consul:latest'
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    networks:
      - services
    command: 'agent -dev -node=bookhub -client=0.0.0.0 -log-level=INFO'
  rabbitMQ:
    image: 'rabbitmq:3-management'
    ports:
      - '15672:15672'
    networks:
      - services
  gateway:
    build:
      context: ../Gateway
      dockerfile: Dockerfile
    image: gateway:latest
    ports:
      - '8000:8000'
    networks:
      - services
    depends_on:
      - rabbitMQ
      - consul
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
  book:
    build:
      context: ../Book
      dockerfile: Dockerfile
    image: book:latest
    ports:
      - '8082:8082'
    networks:
      - services
    depends_on:
      - book_db
      - manager
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:mysql://book_db:3306/book
  comment:
    build:
      context: ../Comment
      dockerfile: Dockerfile
    image: comment:latest
    ports:
      - '8081:8081'
    networks:
      - services
    depends_on:
      - comment_db
      - manager
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_DATASOURCE_URL=jdbc:mysql://comment_db:3306/comment
  manager:
    build:
      context: ../Manager
      dockerfile: Dockerfile
    image: manager:latest
    ports:
      - '8080:8080'
    networks:
      - services
    depends_on:
      - gateway
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=docker
networks:
  services:
    driver: bridge