volumes:
  book_db:
    driver: local
  comment_db:
    driver: local
  user_db:
    driver: local

services:
  book_db:
    image: 'mysql:8.0.33'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: book
    volumes:
      - book_db:/var/lib/mysql
      - ./mysql/book/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    networks:
      - services
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  comment_db:
    image: 'mysql:8.0.33'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: comment
    volumes:
      - comment_db:/var/lib/mysql
      - ./mysql/comment/init:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    networks:
      - services
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  user_db:
    image: 'mysql:8.0.33'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: user
    volumes:
      - user_db:/var/lib/mysql
      - ./mysql/user/init:/docker-entrypoint-initdb.d
    ports:
      - '3308:3306'
    networks:
      - services
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  consul:
    image: 'hashicorp/consul:latest'
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    networks:
      - services
    volumes:
      # Copies the key value pairs from ./consul/consul_kv_docker.json
      - ./consul/consul_kv_docker.json:/kv_import/consul_kv_docker.json
    #command: 'agent -dev -node=bookhub -client=0.0.0.0 -log-level=INFO'
    # Starts consul, then imports key value pairs
    entrypoint: consul agent -dev -node=bookhub -client=0.0.0.0 -log-level=INFO
    post_start:
      - command: sh -c "sleep 5 && consul kv import @/kv_import/consul_kv_docker.json"
    healthcheck:
      test: [ "CMD", "/bin/sh", "-c", "consul kv get -keys | grep -q ." ]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  rabbitMQ:
    image: 'rabbitmq:3.12-management'
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - services

  gateway:
    build:
      context: ../Gateway
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/microservices:${IMAGE_TAG}-gateway
    ports:
      - '8000:8000'
    networks:
      - services
    depends_on:
      - rabbitMQ
      - consul
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul

  book:
    build:
      context: ../Book
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/microservices:${IMAGE_TAG}-book
    deploy:
      replicas: 3
    ports:
      - '8082'
    networks:
      - services
    depends_on:
      book_db:
        condition: service_healthy
      manager:
        condition: service_started
      consul:
        condition: service_healthy
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev

  comment:
    build:
      context: ../Comment
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/microservices:${IMAGE_TAG}-comment
    deploy:
      replicas: 3
    ports:
      - '8081'
    networks:
      - services
    depends_on:
      comment_db:
        condition: service_healthy
      manager:
        condition: service_started
      consul:
        condition: service_healthy
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev

  user:
    build:
      context: ../User
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/microservices:${IMAGE_TAG}-user
    deploy:
      replicas: 3
    ports:
      - '8083'
    networks:
      - services
    depends_on:
      user_db:
        condition: service_healthy
      manager:
        condition: service_started
      consul:
        condition: service_healthy
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev

  manager:
    build:
      context: ../Manager
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/microservices:${IMAGE_TAG}-manager
    ports:
      - '8080:8080'
    networks:
      - services
    depends_on:
      consul:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_PROFILES_ACTIVE=dev

networks:
  services:
    driver: bridge