###
GET localhost:8082/book/fetchAll

###
POST localhost:8082/book/saveOneBook
Content-Type: application/json

{
  "title": "Mistborn",
  "author": "Brandon Sanderson",
  "pages": 345,
  "bookContent": "Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, Hei mitt navn er Stefan, "
}