spring.application.name=book
server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# DOCKER RUN
spring.datasource.url=jdbc:mysql://book_db:3306/book
spring.datasource.username=root
spring.datasource.password=Kakemann
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONSUL
spring.cloud.consul.host=consul

management.endpoints.web.exposure.include=health,info

# RabbitMQ configuration
amqp.exchange.name=bookExchange
amqp.queue.book=bookQueue
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672