CREATE DATABASE IF NOT EXISTS comment;
CREATE SCHEMA IF NOT EXISTS comment;

USE comment;

CREATE TABLE IF NOT EXISTS comment
(
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    page INT NOT NULL,
    positive BOOLEAN NOT NULL,
    negative BOOLEAN NOT NULL,
    comment_text LONGTEXT NOT NULL,
    PRIMARY KEY (id)
);
