spring.application.name=manager
book.service.url=http://book:8082


management.endpoints.web.exposure.include=health,info
spring.config.import=optional:consul:
spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
