name: Build and Push Docker Image

on:
  push:
  #pull_request:
   # types: [closed]
    branches:
      - master
      - refactoring

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Update docker compose
        run: curl -SL https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose

      - name: Set permission for docker-compose
        run: chmod +x /usr/local/bin/docker-compose

      - name: check docker-compose client version
        run: docker-compose version


      - name: Extract short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Set environment variables
        run: echo "IMAGE_TAG=${{ env.SHORT_SHA }}" >> $GITHUB_ENV

      - name: Check Docker version
        run: docker version

      - name: Debug Environment Variables
        run: |
          echo "DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}"
          echo "IMAGE_TAG=${IMAGE_TAG}"
      - name: Build Docker images with docker-compose
        working-directory: ./docker
        run: docker-compose build

      - name: Tag images with 'latest'
        working-directory: ./docker
        run: |
          services=(gateway book comment user manager)
          for service in "${services[@]}"; do
            docker tag "${DOCKERHUB_USERNAME}/microservices:${IMAGE_TAG}-${service}" "${DOCKERHUB_USERNAME}/microservices:latest-${service}"
          done
      - name: Push Docker images
        working-directory: ./docker
        run: |
          services=(gateway book comment user manager)
          for service in "${services[@]}"; do
            docker push "${DOCKERHUB_USERNAME}/microservices:${IMAGE_TAG}-${service}"
            docker push "${DOCKERHUB_USERNAME}/microservices:latest-${service}"
          done